const shopActionTypes = {
  SET_PRODUCTS: 'SET_PRODUCTS',
  CLEAR_PRODUCTS: 'CLEAR_PRODUCTS',
  FETCH_PRODUCTS_START: 'FETCH_PRODUCTS_START',
  FETCH_PRODUCTS_ERROR: 'FETCH_PRODUCTS_ERROR',

  SET_CURRENT_PRODUCT: 'SET_CURRENT_PRODUCT',
  CLEAR_CURRENT_PRODUCT: 'CLEAR_CURRENT_PRODUCT',
  FETCH_CURRENT_PRODUCT_START: 'FETCH_CURRENT_PRODUCT_START',
  FETCH_CURRENT_PRODUCT_ERROR: 'FETCH_CURRENT_PRODUCT_ERROR',

  SET_CATEGORIES: 'SET_CATEGORIES',
  SET_CURRENT_CATEGORY: 'SET_CURRENT_CATEGORY',
  SET_CURRENT_STYLE: 'SET_CURRENT_STYLE',

  ClEAR_CURRENT_STYLE: 'CLEAR_CURRENT_STYLE',
  'CLEAR_CURRENT_CATEGORY': 'CLEAR_CURRENT_CATEGORY'
}

export default shopActionTypes