const shopActionTypes = {
  SET_PRODUCTS: 'SET_PRODUCTS',
  SET_CURRENT_PRODUCT: 'SET_CURRENT_PRODUCT',
  SET_TOTAL_PRODUCTS: 'SET_TOTAL_PRODUCTS',
  SET_CATEGORIES: 'SET_CATEGORIES',
  SET_CURRENT_CATEGORY: 'SET_CURRENT_CATEGORY',
  SET_CURRENT_STYLE: 'SET_CURRENT_STYLE',

  CLEAR_PRODUCTS: 'CLEAR_PRODUCTS',
  CLEAR_CURRENT_PRODUCT: 'CLEAR_CURRENT_PRODUCT',
  ClEAR_CURRENT_STYLE: 'CLEAR_CURRENT_STYLE',
  'CLEAR_CURRENT_CATEGORY': 'CLEAR_CURRENT_CATEGORY'
}

export default shopActionTypes