const cartActionTypes = {
  SET_CART_ITEM_START: 'SET_CART_ITEM_START',
  SET_CART_ITEM_ERROR: 'SET_CART_ITEM_ERROR',
  SET_CART_ITEM: 'SET_CART_ITEM',

  DELETE_FROM_CART_START: 'DELETE_FROM_CART_START',
  DELETE_FROM_CART_ERROR: 'DELETE_FROM_CART_ERROR',
  DELETE_FROM_CART: 'DELETE_FROM_CART',

  GET_CART_START: 'GET_CART_START',
  SET_CART: 'SET_CART',
  GET_CART_ERROR: 'GET_CART_ERROR',

  EMPTY_CART: 'EMPTY_CART'
}

export default cartActionTypes