const cartActionTypes = {
  SET_CART_ITEM_START: 'SET_CART_ITEM_START',
  SET_CART_ITEM_ERROR: 'SET_CART_ITEM_ERROR',
  SET_CART_ITEM: 'SET_CART_ITEM',

  REMOVE_CART_ITEM: 'REMOVE_CART_ITEM',

  DELETE_FROM_CART_START: 'DELETE_FROM_CART_START',
  DELETE_FROM_CART_ERROR: 'DELETE_FROM_CART_ERROR',
  DELETE_FROM_CART: 'DELETE_FROM_CART'
}

export default cartActionTypes