const favoritesActionTypes = {
  SET_FAVORITE_START: 'SET_FAVORITE_START',
  SET_FAVORITE_ERROR: 'SET_FAVORITE_ERROR',
  SET_FAVORITE_ITEM: 'SET_FAVORITE_ITEM',

  DELETE_FAVORITE_START: 'DELETE_FAVORITE_START',
  DELETE_FAVORITE_ERROR: 'DELETE_FAVORITE_ERROR',
  DELETE_FAVORITE: 'DELETE_FAVORITE',

  GET_FAVORITES_START: 'GET_FAVORITES_START',
  GET_FAVORITES_ERROR: 'GET_FAVORITES_ERROR',
  SET_FAVORITES: 'SET_FAVORITES'
}

export default favoritesActionTypes;