const userActionTypes = {
  USER_SIGN_IN_START: 'USER_SIGN_IN_START',
  USER_SIGN_IN_ERROR: 'USER_SIGN_IN_ERROR',
  SET_USER: 'SET_USER',
  CLEAR_USER: 'CLEAR_USER',

  USER_REFRESH_START: 'USER_REFRESH_START',
  USER_REFRESH_ERROR: 'USER_REFRESH_ERROR',
  SET_ACCESS_TOKEN: 'SET_ACCESS_TOKEN'
}

export default userActionTypes