const userActionTypes = {
  USER_SIGN_IN_START: 'USER_SIGN_IN_START',
  USER_SIGN_IN_ERROR: 'USER_SIGN_IN_ERROR',
  SET_USER: 'SET_USER',
  CLEAR_USER: 'CLEAR_USER',

  USER_SIGN_UP_START: 'USER_SIGN_UP_START',
  USER_SIGN_UP_END: 'USER_SIGN_UP_END',
  USER_SIGN_UP_ERROR: 'USER_SIGN_UP_ERROR',

  USER_REFRESH_START: 'USER_REFRESH_START',
  USER_REFRESH_ERROR: 'USER_REFRESH_ERROR',
  SET_ACCESS_TOKEN: 'SET_ACCESS_TOKEN',

  USER_VALIDATE_START: 'USER_VALIDATE_START',
  USER_VALIDATE_SUCCESS: 'USER_VALIDATE_SUCCESS',

  CLEAR_ERROR: 'CLEAR_ERROR'
}

export default userActionTypes