"""add favorites

Revision ID: 132c09965ecf
Revises: 27f1a2ef1dce
Create Date: 2022-05-16 23:55:56.954116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '132c09965ecf'
down_revision = '27f1a2ef1dce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('style_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['style_id'], ['product_styles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'style_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    # ### end Alembic commands ###
