"""add cart table

Revision ID: 27f1a2ef1dce
Revises: 9f8f54b4e425
Create Date: 2022-04-23 23:03:25.698309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27f1a2ef1dce'
down_revision = '9f8f54b4e425'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_items',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_style_id', sa.Integer(), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_style_id'], ['product_styles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'product_style_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart_items')
    # ### end Alembic commands ###
